### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Zoriot** [liz3/SkIDE#1]
OS: Windows 10 amd64
Java: 1.8.0_191-b12
SK-IDE version: 2019.1u4
Time: 10.9.2020 18:45:55
 org.json.JSONException: A JSONArray text must start with '[' at 0 [character 1 line 1]
 	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
 	at org.json.JSONArray.<init>(JSONArray.java:108)
 	at org.json.JSONArray.<init>(JSONArray.java:161)
 	at com.skide.utils.ResourceManager.parseSkriptVersions(ResourceManager.kt:31)
 	at com.skide.utils.ResourceManager.loadResources(ResourceManager.kt:109)
 	at com.skide.CoreManager$bootstrap$1$task$1.call(CoreManager.kt:105)
 	at com.skide.CoreManager$bootstrap$1$task$1.call(CoreManager.kt:65)
 	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	at java.lang.Thread.run(Thread.java:748)

Active Windows:
   Name: Error
    Controller: com.skide.gui.controllers.ErrorReportGUIController@7309b0f7

Projects open:

Servers:

Holders projects:

Holders servers:

**Comment by ghost** [comment]
me too

**Comment by Thefirstalpha** [comment]
some details from the java console
```
nov. 09, 2020 9:56:54 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.191 by JavaFX runtime of version 8.0.181
[9.11.2020 09:56:56 | ERROR] org.json.JSONException: A JSONArray text must start with '[' at 0 [character 1 line 1]
[9.11.2020 09:56:56 | ERROR]    at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
[9.11.2020 09:56:56 | ERROR]    at org.json.JSONArray.<init>(JSONArray.java:109)
[9.11.2020 09:56:56 | ERROR]    at org.json.JSONArray.<init>(JSONArray.java:162)
[9.11.2020 09:56:56 | ERROR]    at com.skide.utils.ResourceManager.parseSkriptVersions(ResourceManager.kt:30)
[9.11.2020 09:56:56 | ERROR]    at com.skide.utils.ResourceManager.loadResources(ResourceManager.kt:111)
[9.11.2020 09:56:56 | ERROR]    at com.skide.CoreManager$bootstrap$1$task$1.call(CoreManager.kt:130)
[9.11.2020 09:56:56 | ERROR]    at com.skide.CoreManager$bootstrap$1$task$1.call(CoreManager.kt:108)
[9.11.2020 09:56:56 | ERROR]    at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
[9.11.2020 09:56:56 | ERROR]    at java.util.concurrent.FutureTask.run(Unknown Source)
[9.11.2020 09:56:56 | ERROR]    at java.lang.Thread.run(Unknown Source)
nov. 09, 2020 9:56:57 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.191 by JavaFX runtime of version 8.0.181
```

**Comment by toonystank** [comment]
```
Update

SkIDE had the luxury of a fully automated Installer and updater.
The installer from the website will still work, but the updater wont. It will always fail.
Thats due to do the fact that i am no longer keeping the domain 21xayah.com
The old updater was a complex system and i dont have the motivation to rewrite it and repack all the installers.

BUT to not leave this untouched i refactored the Launcher into a simple script which will update existing installations.
The script comes packed and you do not need to have anything else installed.``` 

Repo: [](https://github.com/liz3/SkIDE-launcher)
Downloads: [](https://github.com/liz3/SkIDE-launcher/releases/tag/1.1)

quote from discord server

**Comment by liz3** [comment]
I will not provide support for the old versions, follow the comment @toonystank made

**Comment by liz3** [comment]
see: https://github.com/liz3/SkIDE/issues/3#issuecomment-757093253
