### ISSUE TITLE
JSONArray text must start with "["

### ISSUE THREAD

**Issue by Nostalgia-3** [liz3/SkIDE#4]
**Describe the bug**
I am not sure exactly what it is, but it happens when I begin the application.

**To Reproduce**
1. Go to 'https://skide.liz3.net/'
2. Click on the 'download' button
3. Run Application

**Expected behavior**
I expected for it to open and be able to use.

**Desktop (please complete the following information):**
 - OS: Windows 10 amd64
 - Browser: Google Chrome
 - Version 2019.1u4

**Additional context**
This is the error that popped up.
```
OS: Windows 10 amd64
Java: 1.8.0_191-b12
SK-IDE version: 2019.1u4
Time: 10.1.2021 14:54:11
 org.json.JSONException: A JSONArray text must start with '[' at 0 [character 1 line 1]
 	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
 	at org.json.JSONArray.<init>(JSONArray.java:108)
 	at org.json.JSONArray.<init>(JSONArray.java:161)
 	at com.skide.utils.ResourceManager.parseSkriptVersions(ResourceManager.kt:31)
 	at com.skide.utils.ResourceManager.loadResources(ResourceManager.kt:109)
 	at com.skide.CoreManager$bootstrap$1$task$1.call(CoreManager.kt:105)
 	at com.skide.CoreManager$bootstrap$1$task$1.call(CoreManager.kt:65)
 	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by AyhamAl-Ali** [comment]
Same on Linux, it also says "Failed to check for updates" when I launch it

```
OS: Linux amd64
Java: 1.8.0_191-b12
SK-IDE version: 2019.1u4
Time: 4.2.2021 01:25:39
 org.json.JSONException: A JSONArray text must start with '[' at 0 [character 1 line 1]
 	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
 	at org.json.JSONArray.<init>(JSONArray.java:108)
 	at org.json.JSONArray.<init>(JSONArray.java:161)
 	at com.skide.utils.ResourceManager.parseSkriptVersions(ResourceManager.kt:31)
 	at com.skide.utils.ResourceManager.loadResources(ResourceManager.kt:109)
 	at com.skide.CoreManager$bootstrap$1$task$1.call(CoreManager.kt:105)
 	at com.skide.CoreManager$bootstrap$1$task$1.call(CoreManager.kt:65)
 	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by liz3** [comment]
@AyhamAl-Ali @LegotronForce these are both outdated versions please check the #1 issue and the discord
