### ISSUE TITLE
Error while "Reading skript versions"

### ISSUE THREAD

**Issue by Quik2007** [liz3/SkIDE#5]
**Describe the bug**
While SkIDE is loading (Status: "Reading Script Versions) a SkIDE Error window opens.

**To Reproduce**
1. Start SkIDE with Ubuntu.

**Expected behavior**

**Screenshots**
![Bildschirmfoto von 2021-02-15 09-41-30](https://user-images.githubusercontent.com/58744513/107923660-15f0f580-6f72-11eb-9f73-0f275cb57801.png)

**Desktop (please complete the following information):**
 - OS: Linux (Debian, Ubuntu 20.04)

**Error**
OS: Linux amd64
Java: 1.8.0_191-b12
SK-IDE version: 2019.1u4
Time: 15.2.2021 09:44:50
 org.json.JSONException: A JSONArray text must start with '[' at 0 [character 1 line 1]
 	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
 	at org.json.JSONArray.<init>(JSONArray.java:108)
 	at org.json.JSONArray.<init>(JSONArray.java:161)
 	at com.skide.utils.ResourceManager.parseSkriptVersions(ResourceManager.kt:31)
 	at com.skide.utils.ResourceManager.loadResources(ResourceManager.kt:109)
 	at com.skide.CoreManager$bootstrap$1$task$1.call(CoreManager.kt:105)
 	at com.skide.CoreManager$bootstrap$1$task$1.call(CoreManager.kt:65)
 	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	at java.lang.Thread.run(Thread.java:748)

**Comment by Luppyn** [comment]
This error still happening
