### ISSUE TITLE
Expectation. 

### ISSUE THREAD

**Issue by EldariaDevelopment** [liz3/SkIDE#7]
OS: Windows 10 amd64
Java: 1.8.0_291-b10
SK-IDE version: 2021.0.2
Time: 21.2.2022 00:18:44
 java.io.IOException: There is not enough space on the disk
 	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
 	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:75)
 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
 	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
 	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211)
 	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
 	at java.nio.channels.Channels.writeFully(Channels.java:101)
 	at java.nio.channels.Channels.access$000(Channels.java:61)
 	at java.nio.channels.Channels$1.write(Channels.java:174)
 	at java.nio.file.Files.write(Files.java:3297)
 	at com.skide.utils.FileUtilsKt.writeFile(FileUtils.kt:63)
 	at com.skide.utils.FileUtilsKt.writeFile$default(FileUtils.kt:49)
 	at com.skide.core.management.OpenProjectManager$saveCode$1$1.run(OpenProjectManager.kt:98)
 	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
 	at java.security.AccessController.doPrivileged(Native Method)
 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
 	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
 	at java.lang.Thread.run(Thread.java:748)

**Comment by EldariaDevelopment** [comment]
oh I just didn't have enough memory lol
